#!/usr/bin/python
# coding=utf-8

# TODO: cd after exit

from code import debug, fm, ui, options, environment

# TODO: find out the real name of this script and include files relative to here

# TODO: Parse arguments

# TODO: load config

def main():
	import locale
	locale.setlocale(locale.LC_ALL, 'en_US.utf8')

	path = '.'
	opt = options.get()
	env = environment.Environment()

	my_fm = fm.FM(opt, env)
	my_fm.setup(path, ui.UI(opt))
	my_fm.run()

if __name__ == "__main__": main()
