name: Other tests

on: [push, pull_request]

jobs:
  test_py:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.7, 3.x]
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # We need to ignore PyLint because we can't install the one we need for
        # Python 2.7 and 3.5
        pip install -r <(grep -v pylint requirements.txt)
    - name: Get changed Python files
      uses: dorny/paths-filter@v2
      id: paths-filter
      with:
        filters: |
          code:
            - added|modified: '!(ranger/config)**.py'
    - name: Other tests
      if: ${{ steps.path-filter.outputs.code == 'true' }}
      run: |
        make test_doctest test_other
