name: Shellcheck scope.sh

on: 
  push:
    paths:
      - '.github/workflows/shellcheck.yml'
      - 'ranger/data/scope.sh'

jobs:
  test_shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install newer shellcheck (0.7.0 rather than 0.4.6)
      run: |
        curl -LO "https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz"
        tar xf shellcheck-stable.linux.x86_64.tar.xz
    - name: Shellcheck scope.sh
      run: |
        env PATH=shellcheck-stable:$PATH make test_shellcheck
